DROP DATABASE IF EXISTS bingbong;
CREATE DATABASE bingbong;
USE bingbong;
CREATE TABLE feeds(
    url VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY(url)
)CHARSET = UTF8MB4;

CREATE TABLE subscriptions(
    sid BIGINT AUTO_INCREMENT NOT NULL,
    url VARCHAR(100) NOT NULL,
    subscriber BIGINT NOT NULL,
    isGroup BOOLEAN NOT NULL,
    PRIMARY KEY(sid),
    FOREIGN KEY(url) REFERENCES feeds(url)
)CHARSET = UTF8MB4;

CREATE TABLE hashes(
    fid BIGINT AUTO_INCREMENT NOT NULL,
    url VARCHAR(100) NOT NULL,
    hash VARCHAR(100) NOT NULL,
    PRIMARY KEY(fid),
    FOREIGN KEY(url) REFERENCES feeds(url)
)CHARSET = UTF8MB4;