name: release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: publish releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: Build and Release
        run: make
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
